listen:
  address: ":9130"
  metricspath: "/metrics"
modems:
  -
    address: "http://192.168.100.1"
    username: "user"
    password: "pass"
    timeout: "5s"
  -
    address: "http://10.0.100.1"
    username: "admin"
    password: "secret"
    timeout: "5s"